In [72]:
# Importation des bibliothèques nécessaires
# pandas : pour la manipulation des données
# numpy : pour les calculs numériques
import pandas as pd
import numpy as np

# Importation des fonctions spécifiques de sklearn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split  # Pour diviser les données en ensembles d'entraînement et de test
from sklearn.linear_model import LogisticRegression  # Pour entraîner un modèle de régression logistique
from sklearn.metrics import confusion_matrix  # Pour calculer la matrice de confusion
from sklearn.metrics import roc_auc_score  # Pour calculer le score ROC-AUC
from sklearn.metrics import classification_report  # Pour générer un rapport de classification

In [73]:
# Chargement du jeu de données Iris
# La fonction load_iris permet de charger un jeu de données intégré à sklearn
# X contient les variables prédictives, y contient les étiquettes de classe
X, y = load_iris(return_X_y=True)

In [74]:
# Division des données en ensembles d'entraînement et de test
# 80% des données seront utilisées pour l'entraînement, 20% pour le test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=8)

In [75]:
# Entraînement du modèle de régression logistique
# Le modèle est initialisé avec un random_state pour garantir la reproductibilité
clf = LogisticRegression(random_state=8).fit(X_train, y_train)

In [76]:
# Prédictions sur l'ensemble de test
# y_pred contient les classes prédites
# y_pred_proba contient les probabilités associées à chaque classe
y_pred = clf.predict(X_test)
y_pred_proba = clf.predict_proba(X_test)

In [77]:
# Calcul et affichage de la matrice de confusion
# La matrice de confusion permet d'évaluer les performances du modèle en comparant les prédictions aux vraies étiquettes
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

[[10  0  0]
 [ 0  8  1]
 [ 0  2  9]]


In [78]:
# Calcul du score ROC-AUC
# Le score ROC-AUC mesure la capacité du modèle à distinguer entre les classes
# multi_class='ovr' indique que le calcul est fait en mode "un contre tous"
print("ROC-AUC", roc_auc_score(y_test, clf.predict_proba(X_test), multi_class='ovr'))

ROC-AUC 0.9865657409517059


In [79]:
# Affichage du rapport de classification
# Le rapport de classification fournit des métriques telles que la précision, le rappel, et le score F1 pour chaque classe
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.80      0.89      0.84         9
           2       0.90      0.82      0.86        11

    accuracy                           0.90        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.90      0.90      0.90        30

